name: pyinstaller 
on: workflow_dispatch 

jobs:
    build-on-macos:
        runs-on: macos-12
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install pyinstaller
              run: pip install pyinstaller
            - name: build exe
              run: pyinstaller sh256.py -F
            
