name: newenv
on: 
    workflow_dispatch:

# env:
#     DB_U: ${{vars.DB_USERNAME}}
#     DB_P: ${{secrets.DB_PASSWORD}}

jobs:
    test-secrets:
        environment: test
        env:
            DB_U: ${{vars.DB_USERNAME}}
            DB_P: ${{secrets.DB_PASSWORD}}
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: check var from env u
              run: echo "u=${{env.DB_U}}"
            - name: chech env p
              run: echo "p=${{secrets.DB_P}}"
            - name: test with py
              run: python secrets.py
    prod-secrets:
        environment: prod
        env: 
            DB_U: ${{vars.DB1_USERNAME}}
            DB_P: ${{secrets.DB1_PASSWORD}}
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: check var from env u
              run: echo "u=${{env.DB_U}}"
            - name: chech env p
              run: echo "p=${{secrets.DB_P}}"
            - name: test with py
              run: python secrets.py