name: workflow_secrets
on: 
    workflow_dispatch:

# env:
#     DB_U: ${{vars.DB_USERNAME}}
#     DB_P: ${{secrets.DB_PASSWORD}}

jobs:
    test-secrets:
        env:
            DB_U: ${{vars.DB_USERNAME}}
            DB_P: ${{secrets.DB_PASSWORD}}
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: check var from env u
              run: echo "u=${{env.DB_U}}"
            #   run: echo "u=${{vars.DB_USERNAME}}"
            - name: chech env p
              run: echo "p=${{env.DB_P}}"
            #   run: echo "p = ${{env.DB_PASSWORD}}"
            - name: test with py
              run: python secrets.py
    apply-jobs:
        env: 
            DB_U: ${{vars.DB1_USERNAME}}
            DB_P: ${{secrets.DB1_PASSWORD}}
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
